name "workstations"
maintainer "Chef Community Engineering"
maintainer_email "community@chef.io"
license "Apache 2.0"
description "Installs/Configures workstations used in trainings/workshops, meant to be used with Packer"
long_description "Installs/Configures workstations used in trainings/workshops, meant to be used with Packer"
version "0.1.0"

depends "sudo"
depends "chef-ingredient"
depends "selinux"
